# Generated by Django 4.1.7 on 2023-03-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_review_options_alter_review_rating'),
        ('accounts', '0003_alter_account_commented_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='commented_products',
            field=models.ManyToManyField(related_name='user_comments', to='products.product', verbose_name='Отзыв на товары'),
        ),
    ]
