# Generated by Django 4.1.7 on 2023-03-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_commented_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='commented_products',
        ),
    ]
